# The URL the site will be built for
base_url = "https://prismata.press"

title = "Prismata Press"
author = "Prismata Press Limited"
description = "A trans-owned and operated micro press"


# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

generate_feeds = true
feed_filenames = [ "atom.xml",]
minify_html = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme = "vonge"
taxonomies = [
    { name = "themes", feed = true},
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
# highlight_code = false

[extra]
# Put all your custom variables here

logo_image = "images/Prismata_Press_Logo.png"

author_image = '/images/SophMoth_Bookems.png'
social_media_share_image = "/images/SophMoth_Bookems.png"

navigation = [
    { url = "$BASE_URL", title = "Home" },
    { url = "$BASE_URL/books", title = "Books" },
    { url = "$BASE_URL/posts", title = "Posts" },
    { url = "$BASE_URL/links", title = "Links" },
    { url = "$BASE_URL/content_warnings", title = "Content Warnings" },
]

social_icons = [
    { url = "https://bsky.app/profile/prismata.press", name = "Bluesky" },
    { url = "https://rss.com/podcasts/galaxy-moth", name = "Podcast" },
    { url = "https://www.instagram.com/transistance.press", name = "Instagram"},
    { url = "$BASE_URL/atom.xml", name = "RSS" },
]

[[extra.content_blocks]]
block = "hero"
title = "Prismata Press"
description_html = "Nestled among the volcanoes of New Zealand, Prismata Press is a fiery trans-owned and operated micro-press with a passion for sharing trans voices. We publish fiction and poetry in e-book, print, and audio formats."
image = "/images/SophMoth_Bookems.png"
image_alt = "Prismata Press Icon"

